config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :meetings
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

devise_for :users
 
	root :to => 'home#index'

   root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :meetings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = current_user.meetings.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    @meeting.user_id = current_user.id
    
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
   # @meeting.destroy
   # respond_to do |format|
   #   format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
    #  format.json { head :no_content }
   # end

   @meeting = Meeting.find(params[:id])
  @meeting.destroy

  redirect_to meetings_path
 
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, 
                                      :start_hour, :start_minute, 
                                      :end_hour, :end_minute,   
                                      :user_id, 
                                      :monday, :tuesday, :wednesday, :thursday, :friday, 
                                      :comment, :teacher, :stock, :place, :equipment)
    end

    def current
      ::Time.zone ? ::Time.zone.today : ::Date.today
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def readable_time(time)
		time.strftime("%b %d, %I:%M%P")
	end

	def author_of(record)
		user_signed_in? && current_user.id == record.user_id
	end

	def admin? 
		user_signed_in? && current_user.admin?
	end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/home/index.html.erb
<h1 class="semibold text-2xl">Welcome!!</h1>
<p class="lead"> Bienvenido a la pagina</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>


<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">ReservApp</a>
    </div>
    <ul class="nav navbar-nav">
          <% unless user_signed_in? %>
              <li class="active"><a href="#">Home</a></li>
              <li><a href=/users/sign_in>Log in</a></li>
              <li><a href=/users/sign_up>Sign up</a></li>       
          <%  else %>
              <li><a href=../meetings/>Mis reservas</a></li>
              <li><a href=../meetings/new>Nueva reserva</a></li>
              <li><a href=../../users/sign_out>Salir</a></li>
          <% end %>
    </ul>
  </div>
</nav>
   

<html>
  <head>
    <title>Kickstart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag "application" %>

<% javascript_include_tag "application" %>
 
    <%javascript_include_tag "https://js.stripe.com/v3", 'data-turbolink-track':'reload'%>
    <%tag :meta, name: "stripe-public-key", content: Rails.application.credentials.stripe_publishable_key%>
  </head>

 <body class="bg-grey-lighter">

  <% flash.each do |type, message| %>
    <% if type == "alert" %>
      <div class="bg-red-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
    <% if type == "notice" %>
      <div class="bg-green-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
  <% end %>

    

    <main class="lg:px-10 px-4">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/meetings/_calendar.html.erb
<%= month_calendar events: meetings do |date, meetings| %>
  <%= date %>
  <% meetings.each do |meeting| %>
    <div>
      <%= link_to meeting.name, meeting, class: "link" %>
    </div>
  <% end %>
<% end %>

app/views/meetings/_form.html.erb
<%=  form_with(model: meeting, local: true) do |form| %>

  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <%= simple_form_for @meeting do |f| %>
     <div class="container">
      <br/><br/> 
      <div class="col-sm-2"></div>
      <div class="col-sm-8">

          <div class="col-md">
       
            <table class="table">
              <tbody> 
                  

                <tr>
                     <%= f.input :name %>
                </tr>

                <tr>
                     <%= f.input :teacher %>
                </tr>

                <tr>
                     <%= f.input :stock %>
                </tr>

                <tr>
                     <%= f.input :equipment %>
                </tr>

                <tr>
                     <%= f.input :place %>
                </tr>

                <tr>
                     <%= f.input :comment %>
                </tr>
                <!--tr>
              <%= f.collection_select :id, Meeting.order(:name),:id,:name, include_blank: true %>
                </tr-->

                <tr>
                  <th scope="row">Lunes</th>
                  <td><%= form.select :monday, ['SI', 'NO'], class: "form-control"%></td> 
                </tr>
                <tr>
                  <th scope="row">Martes</th>
                  <td><%= form.select :tuesday, ['SI', 'NO'], class: "form-control"%></td> 
                </tr>
                <tr>
                  <th scope="row">Miercoles</th>
                  <td><%= form.select :wednesday, ['SI', 'NO'], class: "form-control"%></td> 
                </tr>
                <tr>
                  <th scope="row">Jueves</th>
                  <td><%= form.select :thursday, ['SI', 'NO'], class: "form-control"%></td> 
                </tr>
                <tr>
                  <th scope="row">Viernes</th>
                  <td><%= form.select :friday, ['SI', 'NO'], class: "form-control"%></td> 
                </tr>

                <tr>
                  <th scope="row">Hora Inicio</th>
                  <td><%= form.select :start_hour, ['7', '8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23'], class: "form-control"%> 
                  <%= form.select :start_minute, ['00','05','10','15','20','25','30','35','40','45','50','55'], class: "form-control"%></td> 
                </tr>
 

                <tr>
                  <th scope="row">Hora Fin</th>
                  <td><%= form.select :end_hour, ['7', '8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23'], class: "form-control"%> 
                  <%= form.select :end_minute, ['00','05','10','15','20','25','30','35','40','45','50','55'], class: "form-control"%></td> 
                </tr>


                <tr>
                  <th scope="row">  
                    <%= f.button :submit, class: "btn-primary" %>
                      <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
                      <%= link_to 'Back', meetings_path %>

                  </th>
                  <td></td> 
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      <% end %>
      <% end %>
    </div> 

app/views/meetings/_meeting_landing.html.erb
<nav class="bg-white mb-4 shadow rounded">
  <ul id="nav-tab" class="tabs list-reset flex">

    <li class="active" data-tab="calendar">
      <%= link_to "#calendar", class: "tab flex items-center" do %>
       <svg viewBox="0 0 20 20" width="16" height="16" class="fill-current text-grey-light mr-2"><title>calendar</title><path d="M1 4c0-1.1.9-2 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4zm2 2v12h14V6H3zm2-6h2v2H5V0zm8 0h2v2h-2V0zM5 9h2v2H5V9zm0 4h2v2H5v-2zm4-4h2v2H9V9zm0 4h2v2H9v-2zm4-4h2v2h-2V9zm0 4h2v2h-2v-2z"></path></svg>
       Calendar
      <% end %>
    </li>

     <li data-tab="all-meetings">
      <%= link_to "#all-meetings", class: "tab flex items-center" do %>
        <svg viewBox="0 0 20 20" class="fill-current text-grey-light mr-2" width="16" height="16"><title>coffee</title><path d="M4 11H2a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2h2V1h14v10a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4zm0-2V5H2v4h2zm-2 8v-1h18v1l-4 2H6l-4-2z"></path></svg>
      All Meetings
      <% end %>
    </li>

  </ul>
</nav>

<div class="bg-white p-10 border rounded">
  <div id="all-meetings" class="tab-panel">

     <h1>Meetings</h1>

     <% meetings.each do |meeting| %>
        <div class="flex flex-wrap items-center justify-start p-4 border-b border-grey-light mb-6">
          <div class="flex-1 flex justify-between">
            <div>
              <%= link_to meeting.name, meeting, class: "link mr-4" %>
            </div>
            <div>
              <%= readable_time(meeting.start_time) %> &ndash;
              <%= readable_time(meeting.end_time) %>
            </div>
          </div>
        </div>

        <%= link_to "Cancel Meeting", meeting, method: :delete, data: { confirm: "Are you sure? There are no refunds." }, class: "btn btn-destroy ml-4" if admin? %>
     <% end %>
  </div>

  <div id="calendar" class="tab-panel active">
    <h2>Meeting Calendar</h2>
    <div id="meeting-calendar">
      <%= render "calendar", meetings: meetings  %>
    </div>
  </div>
</div>

app/views/meetings/edit.html.erb
<div class='title'> Editar Reserva </div>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<%= stylesheet_link_tag "application" %>

<p id="notice"><%= notice %></p>

<div class="title">Proximos eventos</div>
<div class="container">
  

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Actividad</th>
          <th scope="col">Dia</th>
          <th scope="col">Hora Inicio</th>
          <th scope="col">Hora fin</th>
          <th scope="col">Profesor</th>
          <th scope="col">Cupos</th>
          <th scope="col">Lugar</th>
          <th scope="col">Equipamiento</th>
          <th scope="col">Comentarios</th>
          <th scope="col">Monday</th>

          <th scope="col"></th>

        </tr>
      </thead>
      <tbody>
        <% @meetings.each do |meeting| %>
          <tr>
            <td><%= meeting.name %></td>
            <td>@current</td>

            <td><%= meeting.start_hour %>:<%= meeting.start_minute %></td>
            <td><%= meeting.end_hour %>:<%= meeting.start_minute %></td>

            <td><%= meeting.teacher %></td> 
            <td><%= meeting.stock %></td> 
            <td><%= meeting.place %></td> 
            <td><%= meeting.equipment %></td> 
            <td><%= meeting.comment%></td>
            <td><%= meeting.monday%></td>

            <td></td>

            <td><%= link_to 'Ver mas', meeting %></td>
            <td><%= link_to 'Editar', edit_meeting_path(meeting) %></td> 
            <td><%= button_to 'Delete', meeting, method: :delete, :onclick => "return confirm('Are you sure you want to delete this post?')" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br/>
    <strong><%= link_to 'New Meeting', new_meeting_path %></strong>
    <br/>
    <br/>
    <br/>
     
  </div> 



 

app/views/meetings/new.html.erb
<div class='title'> Nueva Reserva </div>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<div class="title">Detalles de la Reserva</div> 
 <br/><br/>
 
 <div class="container">

  <div class="col-sm-2"></div>
  <div class="col-sm-8">

	<div class="col-md">
   
		<table class="table">
 		  <tbody>
		    <tr>
		      <th scope="row">Actividad</th>
		      <td><%= @meeting.name %></td> 
		    </tr>
			<tr>
		      <th scope="row">Dias</th>
		      <td>
		        <% if @meeting.monday == "SI" %>Lunes <%end%>
		        <% if @meeting.tuesday == "SI" %> Martes  <%end%>
		        <% if @meeting.wednesday == "SI" %> Miercoles <%end%>
		        <% if @meeting.thursday == "SI" %> Jueves <%end%>
				<% if @meeting.thursday == "SI" %> Viernes <%end%>
				 <%Date.today%> FF

		      </td> 
		    </tr>

		    <tr>
		      <th scope="row">Hora inicio</th>
		      <td><%= @meeting.start_hour %>:<%= @meeting.start_minute %></td> 
		    </tr>
		    <tr>
		      <th scope="row">Hora fin</th>
		      <td><%= @meeting.end_hour %>:<%= @meeting.end_minute %></td> 
		    </tr>
 
			<tr>
		      <th scope="row">Profesor</th>
		      <td><%= @meeting.teacher %></td> 
		    </tr>

			<tr>
		      <th scope="row">Cupos Disponibles</th>
		      <td><%= @meeting.stock %></td> 
		    </tr>

			<tr>
		      <th scope="row">Lugar</th>
		      <td><%= @meeting.place %></td> 
		    </tr>

			<tr>
		      <th scope="row">Comentarios</th>
		      <td><%= @meeting.comment %></td> 
		    </tr>

			<tr>
		      <th scope="row">Materiales necesarios</th>
		      <td><%= @meeting.equipment %></td> 
		    </tr>

			<tr>
		      <th scope="row">Commentarios</th>
		      <td><%= @meeting.comment %></td> 
		    </tr>
 

			<tr>
		      <th scope="row"><%= link_to 'Editar', edit_meeting_path(@meeting) %> |
			<%= link_to 'Atras', meetings_path %></th>
		      <td></td> 
		    </tr>
		  </tbody>
		</table>
		</div>
	
  </div>		
  <div class="col-sm-2"></div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>